web/router.ex
defmodule Ticketee.Router do
  use Ticketee.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Ticketee do
    pipe_through :browser # Use the default browser stack

    get "/", ProjectController, :index
    resources "projects", ProjectController do
      resources "tickets", TicketController, only: [:new, :create]
    end

    resources "tickets", TicketController, only: [:show, :edit, :update, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Ticketee do
  #   pipe_through :api
  # end
end

web/models/project.ex
defmodule Ticketee.Project do
  use Ticketee.Web, :model

  schema "projects" do
    field :title, :string
    field :description, :string
    has_many :tickets, Ticketee.Ticket

    timestamps
  end

  after_delete :remove_tickets

  @required_fields ~w(title)
  @optional_fields ~w(description)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If `params` are nil, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  defp remove_tickets(changeset) do
    Ticketee.Repo.delete_all assoc(changeset.model, :tickets)
    changeset
  end
end

web/controllers/project_controller.ex
defmodule Ticketee.ProjectController do
  use Ticketee.Web, :controller
  alias Ticketee.Project

  plug :scrub_params, "project" when action in [:create, :update]
  plug :load_project when action in [:edit, :update, :show, :delete]

  def index(conn, _) do
    projects = Repo.all(Project)
    render conn, :index, projects: projects
  end

  def new(conn, _) do
    changeset = Project.changeset(%Project{})
    render conn, :new, changeset: changeset
  end

  def create(conn, %{"project" => project_params}) do
    changeset = Project.changeset(%Project{}, project_params)
    case Repo.insert(changeset) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project created successfully.")
        |> redirect to: project_path(conn, :show, project)
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Project could not be created.")
        |> render :new, changeset: changeset
    end
  end

  def show(conn, _) do
    tickets = Repo.all assoc(conn.assigns[:project], :tickets)
    render conn, :show, tickets: tickets
  end

  def edit(conn, _) do
    changeset = Project.changeset(conn.assigns[:project])
    render conn, :edit, changeset: changeset
  end

  def update(conn, %{"project" => project_params}) do
    changeset = Project.changeset(conn.assigns[:project], project_params)
    case Repo.update(changeset) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project updated successfully.")
        |> redirect to: project_path(conn, :show, project)
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Project could not be updated.")
        |> render :edit, changeset: changeset
    end
  end

  def delete(conn, _) do
    case Repo.delete(conn.assigns[:project]) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Project deleted successfully.")
        |> redirect to: project_path(conn, :index)
      {:error, project} ->
        conn
        |> put_flash(:error, "Project could not be deleted.")
        |> redirect to: project_path(conn, :show, project)
    end
  end

  defp load_project(conn, _) do
    case Repo.get(Project, conn.params["id"]) do
      nil ->
        conn
        |> put_flash(:error, "The project you were looking for could not be found.")
        |> redirect(to: project_path(conn, :index))
        |> halt
      project ->
        assign(conn, :project, project)
    end
  end
end

web/views/project_view.ex
defmodule Ticketee.ProjectView do
  use Ticketee.Web, :view

  def page_title(:show, assigns), do: assigns[:project].title
  def page_title(action, _) when action in [:new, :create], do: "Create Project"
  def page_title(action, _) when action in [:edit, :update], do: "Edit Project"
  def page_title(_, _),           do: "Projects"

  def submit_label(model) do
    case model.id do
      nil -> "Create Project"
      _   -> "Update Project"
    end
  end
end

web/templates/project/edit.html.eex
<header>
  <h1>Edit Project</h1>
</header>

<%= render "form.html", changeset: @changeset, action: project_path(@conn, :update, @project) %>

web/templates/project/index.html.eex
<header>
  <h1>Projects</h1>
</header>

<ul class="list-inline">
  <li><%= link "New Project", to: project_path(@conn, :new), class: "btn btn-success" %></li>
</ul>

<div id="projects">
  <%= for project <- @projects do %>
    <h2><%= link project.title, to: project_path(@conn, :show, project) %></h2>
    <p><%= project.description %></p>
  <% end %>
</div>

web/templates/project/new.html.eex
<header>
  <h1>New Project</h1>
</header>

<%= render "form.html", changeset: @changeset, action: project_path(@conn, :create) %>

web/templates/project/show.html.eex
<header>
  <h1><%= @project.title %></h1>
</header>

<ul class="list-inline">
  <li><%= link "Edit Project", to: project_path(@conn, :edit, @project), class: "btn btn-primary" %></li>
  <li><%= link "Delete Project", to: project_path(@conn, :delete, @project), method: :delete, class: "btn btn-danger" %></li>
</ul>

<p><%= @project.description %></p>

<header>
  <h2>Tickets</h2>
</header>

<ul class="list-inline">
  <li><%= link "New Ticket", to: project_ticket_path(@conn, :new, @project), class: "btn btn-success" %></li>
</ul>

<ul class="list-unstyled">
<%= for ticket <- @tickets do %>
  <li><strong>#<%= ticket.id %>:</strong> <%= link ticket.title, to: ticket_path(@conn, :show, ticket) %></li>
<% end %>
</ul>